### PR TITLE
Add some more analytics events

### PR DESCRIPTION
**Pull request by alexbfree**
Adds tracking of the animal characteristic filters & search box

### CODE REVIEW

**Comment by camallen** [comment]
@alex - do you want to squash those last commits (they look similar) into one? check out git interactive rebase.

**Comment by alexbfree** [comment]
Yes that's deliberate. each event type is dealt with in a slightly different way. well spotted :-)

**Comment by aweiksnar** [comment]
Can we chat about this today before deploying? It looks like master branch received a force push this morning and the last 6 commits were lost

**Comment by alexbfree** [comment]
@aweiksnar Cam and I trying to figure out what happened here. Which commits are missing? do you still have a copy that you can push to master?

**Comment by aweiksnar** [comment]
Yeah I have them locally, PR #105 adds them back in.

**Comment by camallen** [comment]
@aweiksnar - thanks. 

For reference it was a `git push -f` without a remote / branch specified using the older git config of `push.default=matching` so all local branches on @alexbfree 's computer got pushed to the state they were on his computer (master was last updated on 10th Feb).

**Comment by alexbfree** [comment]
Sorry for the inconvenience @aweiksnar. I did not know until today that push -f affected more than my current branch. Will be more careful in future. Very glad we didn't lose anything!

**Comment by aweiksnar** [comment]
No worries! git happens... Looks like it's all intact again

**Pull request merged**
